export enum ERRORS {
  NO_SEARCHER_ENGINE = 'NO SEARCH ENGINE SETUP',
  RESULT_NOT_FOUND = 'Result NOT FOUND',
  RESOURCE_ERROR = 'RESOURCE ERROR',
  SUBSCRIPTION_ERROR = 'SUBSCRIPTION ERROR',
  BOT_STARTUP_ERROR = 'ERROR ON BOT STARTUP',
  INVALID_URL = 'INVALID URL ERROR',
  INVALID_COMMAND = 'INVALID COMMAND ERROR',
  INVALID_COMMAND_USAGE = 'INVALID COMMAND USAGE ERROR',
}

export enum STATUS_CODES {
  OK = 200,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

export class BotError extends Error {
  public code: STATUS_CODES;
  public constructor(public message: string, public userMessage: string) {
    super(message);
  }
}
