export enum ERRORS {
	NO_SEARCHER_ENGINE = 'NO SEARCH ENGINE SETUP',
	RESULT_NOT_FOUND = 'Result NOT FOUND',
	RESOURCE_ERROR = 'RESOURCE ERROR',
	SUBSCRIPTION_ERROR = 'SUBSCRIPTION ERROR',
	BOT_STARTUP_ERROR = 'ERROR ON BOT STARTUP',
	INVALID_URL = 'INVALID URL ERROR',
	INVALID_COMMAND = 'INVALID COMMAND ERROR',
	INVALID_COMMAND_USAGE = 'INVALID COMMAND USAGE ERROR',
}
