export enum ERRORS {
	NO_SEARCHER_ENGINE = 'NO SEARCH ENGINE SETUP',
	RESULT_NOT_FOUND = 'Result NOT FOUND',
	RESOURCE_ERROR = 'RESOURCE ERROR',
	SUBSCRIPTION_ERROR = 'SUBSCRIPTION ERROR',
	BOT_STARTUP_ERROR = 'ERROR ON BOT STARTUP',
}
